src/Entity/Pokemon.php
<?php

namespace App\Entity;

use App\Repository\PokemonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PokemonRepository::class)]
class Pokemon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $point_de_vie = null;

    #[ORM\Column]
    private ?int $point_attaque = null;

    #[ORM\ManyToMany(targetEntity: Type::class, inversedBy: 'pokemons')]
    private Collection $types;

    #[ORM\ManyToOne(inversedBy: 'pokemons')]
    private ?User $dresseur = null;

    public function __construct()
    {
        $this->types = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
         $this->id = $id;
         return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPointDeVie(): ?int
    {
        return $this->point_de_vie;
    }

    public function setPointDeVie(int $point_de_vie): static
    {
        $this->point_de_vie = $point_de_vie;

        return $this;
    }

    public function getPointAttaque(): ?int
    {
        return $this->point_attaque;
    }

    public function setPointAttaque(int $point_attaque): static
    {
        $this->point_attaque = $point_attaque;

        return $this;
    }

    /**
     * @return Collection<int, Type>
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): static
    {
        if (!$this->types->contains($type)) {
            $this->types->add($type);
        }

        return $this;
    }

    public function removeType(Type $type): static
    {
        $this->types->removeElement($type);

        return $this;
    }

    public function getDresseur(): ?User
    {
        return $this->dresseur;
    }

    public function setDresseur(?User $dresseur): static
    {
        $this->dresseur = $dresseur;

        return $this;
    }
}

src/Form/PokemonType.php
<?php

namespace App\Form;

use App\Entity\Pokemon;
use App\Entity\Type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PokemonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', null,['attr' => ['class' => 'form-control col-12']])
            ->add('point_de_vie', null,['attr' => ['class' => 'form-control col-12']])
            ->add('point_attaque', null,['attr' => ['class' => 'form-control col-12']])
            ->add('types', EntityType::class, [
                'class' => Type::class,
                'choice_label' => 'nom',
                'multiple' => true,
                'expanded' => true,
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pokemon::class ,
        ]);
    }
}

src/Controller/PokemonController.php
<?php

namespace App\Controller;

use App\Entity\Pokemon;
use App\Form\PokemonType;
use App\Repository\PokemonRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pokedex/pokemon')]
class PokemonController extends AbstractController
{
    #[Route('/', name: 'app_pokemon_index', methods: ['GET'])]
    public function index(PokemonRepository $pokemonRepository): Response
    {
        return $this->render('pokemon/index.html.twig', [
            'pokemons' => $pokemonRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_pokemon_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $pokemon = new Pokemon();
        $form = $this->createForm(PokemonType::class, $pokemon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($pokemon);
            $entityManager->flush();

            return $this->redirectToRoute('app_pokemon_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pokemon/new.html.twig', [
            'pokemon' => $pokemon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pokemon_show', methods: ['GET'])]
    public function show(Pokemon $pokemon): Response
    {
        return $this->render('pokemon/show.html.twig', [
            'pokemon' => $pokemon,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pokemon_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pokemon $pokemon, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PokemonType::class, $pokemon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_pokemon_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pokemon/edit.html.twig', [
            'pokemon' => $pokemon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pokemon_delete', methods: ['POST'])]
    public function delete(Request $request, Pokemon $pokemon, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pokemon->getId(), $request->request->get('_token'))) {
            $entityManager->remove($pokemon);
            $entityManager->flush();
        }
        

        return $this->redirectToRoute('app_pokemon_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pokemon/_delete_form.html.twig
<div>
    <form method="post" action="{{ path('app_pokemon_delete', {'id': pokemon.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pokemon.id) }}">
        <button class="btn btn-danger">Delete</button>
    </form>
</div>

templates/pokemon/_form.html.twig
{{ form_start(form) }}
    <div class="card-body">
        <div class="form-group">
            {{form_row(form.nom)}}
        </div>
        <div class="form-group">
            {{form_row(form.point_de_vie)}}
        </div>
        <div class="form-group">
            {{form_row(form.point_attaque)}}
        </div>
        <div class="form-group">
            {% for type in form.types %}
                    {{ form_widget(type) }}
                    {{ form_label(type) }}
            {% endfor %}
        </div>
        <div class="card-footer">
            <div class="flex-row d-flex">
                <button class="btn btn-success mr-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pokemon/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pokemon{% endblock %}

{% block body %}
    <h1 class="text-center">Edit Pokemon : {{ pokemon.nom }}</h1>

    <div class="card">

            {{ include('pokemon/_form.html.twig') }}

                <a class = "btn btn-secondary mr-2" href="{{ path('app_pokemon_index') }}">back to list</a>

                {{ include('pokemon/_delete_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/pokemon/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pokemon index{% endblock %}

{% block body %}
<h1 class="text-center">Pokemon Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Type</th>
            <th>Point_de_vie</th>
            <th>Point_attaque</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
    {% for pokemon in pokemons %}
        <tr>
            <td>{{ pokemon.id }}</td>
            <td>{{ pokemon.nom }}</td>
            <td>
                <ul>
                    {% for type in pokemon.types %}
                        <li><a href="{{ path('app_type_show', {'id': type.id}) }}">{{ type.nom }}</a></li>
                    {% endfor %}
                </ul>
            </td>
            <td>{{ pokemon.pointDeVie }}</td>
            <td>{{ pokemon.pointAttaque }}</td>
            <td>
                <a class="btn btn-primary" href="{{ path('app_pokemon_show', {'id': pokemon.id}) }}">show</a>
                <a class="btn btn-warning" href="{{ path('app_pokemon_edit', {'id': pokemon.id}) }}">edit</a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<a class ="btn btn-success ml-3" href="{{ path('app_pokemon_new') }}">Create new</a>
{% endblock %}

templates/pokemon/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pokemon{% endblock %}

{% block body %}
    <h1 class="text-center">New Pokemon</h1>

    <div class="card">
        {{ include('pokemon/_form.html.twig') }}
            <a  class="btn btn-secondary" href="{{ path('app_pokemon_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}

templates/pokemon/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pokemon{% endblock %}

{% block body %}
    <h1 class="text-center">Pokemon : {{ pokemon.nom }}</h1>

    <div class="card mt-3 mr-3 ml-3">
        <div class="card-body">
            <h5 class="card-title">{{ pokemon.nom }}</h5>
            <div class="card-text card">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Types : 
                        <ul>
                            {% for type in pokemon.types %}
                                <li><a href="{{ path('app_type_show', {'id': type.id}) }}">{{ type.nom }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="list-group-item">Points de vie : {{ pokemon.pointDeVie }}</li>
                    <li class="list-group-item">Points d'attaque : {{ pokemon.pointAttaque }}</li>
                </ul>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <a class = "btn btn-secondary mr-2 ml-4" href="{{ path('app_pokemon_index') }}">back to list</a>
                <a class = "btn btn-warning mr-2" href="{{ path('app_pokemon_edit', {'id': pokemon.id}) }}">edit</a>
                {{ include('pokemon/_delete_form.html.twig') }} </div>
            </div>
        </div>
    </div>
{% endblock %}